#Changing settings here have no effect.  Please copy and paste this into ~/.siriproxy to make the configurations work.

    - name: 'Logic'
	  git: 'git://github.com/Deanmv/Dissertation.git'
      machine: 'local' #Machine should be in the format of eppc://Username:Password@IP or EPPC address for remote machines, and just 'local' if siriproxy and 					   #logic are on the same machine.
  
#Then update with 'rvmsudo siriproxy bundle'